<?php
return [
    'verbes' => [
        'bois',
        'dors',
        'mange',
        'éclate',
        'poutre',
        'fume',
        'arrête',
        'ligotte',
        'pète',
        'mouille',
        'un camion ?',
        'chatouille',
        'enfume',
        'michel',
        'GRABA',
        'énèrve',],
    'cods' => [
        'une roue',
        'du pain',
        'Jean Valjean',
        'la jambe',
        'jet 27',
        'de l\'eau',
        'les fesses',
        'le jeudi',
        'avec amour',
        'carrément',
        'trois fois',
        'la vie',
        'le ricou',
        'ta race',
        'simon',
        'guidou',
        'PHP',
        'avec un doigt',
        'le moisi'
    ],
];
